### PR TITLE
fix: Include TS types declaration in the export

### PR DESCRIPTION
**Pull request by lucasamonrc**

### CODE REVIEW

**Comment by janpieterz** [comment]
Any test in a bundler sample or something you can add for this, e.g. by a `tsc` check? These fields in the package.json are all a little too much "up for interpretation" by consumers.

**Comment by lucasamonrc** [comment]
> Any test in a bundler sample or something you can add for this, e.g. by a `tsc` check? These fields in the package.json are all a little too much "up for interpretation" by consumers.

We could make the web-ui sample TypeScript based with Vite. That way we would know if the package types are messed up or something.

**Comment by janpieterz** [comment]
@lucasamonrc isn't [the main sample](https://github.com/trinsic-id/sdk/tree/main/ui-web/samples) (not a bundler one) already using `vite`? I also use `vite` explicitly [here](https://github.com/trinsic-id/sdk/tree/main/ui-web/samples/bundlers/vite).
https://github.com/trinsic-id/sdk/blob/main/ui-web/samples/package.json

**Comment by lucasamonrc** [comment]
> @lucasamonrc isn't [the main sample](https://github.com/trinsic-id/sdk/tree/main/ui-web/samples) (not a bundler one) [already using `vite`?](https://github.com/trinsic-id/sdk/blob/main/ui-web/samples/package.json) I also use `vite` explicitly [here](https://github.com/trinsic-id/sdk/tree/main/ui-web/samples/bundlers/vite).

Yeah, it is, but it isn't TypeScript based. There's no checking for type declarations when we import the SDK. I'm proposing to use TypeScript in the sample in addition to Vite.

**Comment by janpieterz** [comment]
Gotcha. Let's do it in either one, can you do it?

**Pull request merged**
